---
language: node_js
node_js:
  - 0.10
  - 4
  - 6
before_script:
  - "npm install tslint"
  - "npm install babel-core"
  - "npm install typescript"
cache:
  directories:
  - node_modules
  - packages/create-react-app/node_modules
  - packages/react-scripts/node_modules
script: tasks/e2e.sh
env:
  - USE_YARN=no
  - USE_YARN=yes
